public class Main {
    public static void main(String[] args) {
        Card card1 = new Card ("king", "spades");
        System.out.println(card1);
        Card card2 = new Card ("king", "clubs");
        System.out.println(card2);
        Card card3 = new Card ("king", "hearts");
        System.out.println(card3);
        Card card4 = new Card ("king", "diamonds");
        System.out.println(card4);
        Card card5 = new Card ("queen", "spades");
        System.out.println(card5);
        Card card6 = new Card ("queen", "clubs");
        System.out.println(card6);
        Card card7 = new Card ("queen", "diamonds");
        System.out.println(card7);
        Card card8 = new Card ("queen", "hearts");
        System.out.println(card8);
        Card card9 = new Card ("jack", "spades");
        System.out.println(card9);
        Card card10 = new Card ("jack", "clubs");
        System.out.println(card10);
        Card card11 = new Card ("jack", "hearts");
        System.out.println(card11);
        Card card12 = new Card ("jack", "diamonds");
        System.out.println(card12);
        Card card13 = new Card ("ace", "spades");
        System.out.println(card13);
        Card card14 = new Card ("ace", "clubs");
        System.out.println(card14);
        Card card15 = new Card ("ace", "hearts");
        System.out.println(card15);
        Card card16 = new Card ("ace", "diamonds");
        System.out.println(card16);
        Card card17 = new Card ("2", "spades");
        System.out.println(card17);
        Card card18 = new Card ("2", "clubs");
        System.out.println(card18);
        Card card19 = new Card ("2", "hearts");
        System.out.println(card19);
        Card card20 = new Card ("2", "diamonds");
        System.out.println(card20);
        Card card21 = new Card ("3", "spades");
        System.out.println(card21);
        Card card22 = new Card ("3", "clubs");
        System.out.println(card22);
        Card card23 = new Card ("3", "hearts");
        System.out.println(card23);
        Card card24 = new Card ("3", "diamonds");
        System.out.println(card24);
        Card card25= new Card ("4", "spades");
        System.out.println(card25);
        Card card26= new Card ("4", "clubs");
        System.out.println(card26);
        Card card27= new Card ("4", "hearts");
        System.out.println(card27);
        Card card28= new Card ("4", "diamonds");
        System.out.println(card28);
        Card card29= new Card ("5", "spades");
        System.out.println(card29);
        Card card30= new Card ("5", "clubs");
        System.out.println(card30);
        Card card31= new Card ("5", "hearts");
        System.out.println(card31);
        Card card32= new Card ("5", "diamond");
        System.out.println(card32);
        Card card33= new Card ("6", "spades");
        System.out.println(card33);
        Card card34= new Card ("6", "clubs");
        System.out.println(card34);
        Card card35= new Card ("6", "hearts");
        System.out.println(card35);
        Card card36= new Card ("6", "diamonds");
        System.out.println(card36);
        Card card37= new Card ("7", "spades");
        System.out.println(card37);
        Card card38= new Card ("7", "clubs");
        System.out.println(card38);
        Card card39= new Card ("7", "hearts");
        System.out.println(card39);
        Card card40= new Card ("7", "diamonds");
        System.out.println(card40);
        Card card41= new Card ("8", "spades");
        System.out.println(card41);
        Card card42= new Card ("8", "clubs");
        System.out.println(card42);
        Card card43= new Card ("8", "hearts");
        System.out.println(card43);
        Card card44= new Card ("8", "diamonds");
        System.out.println(card44);
        Card card45= new Card ("9", "spades");
        System.out.println(card45);
        Card card46= new Card ("9", "clubs");
        System.out.println(card46);
        Card card47= new Card ("9", "hearts");
        System.out.println(card47);
        Card card48= new Card ("9", "diamonds");
        System.out.println(card48);
        Card card49= new Card ("10", "spades");
        System.out.println(card49);
        Card card50= new Card ("10", "clubs");
        System.out.println(card50);
        Card card51= new Card ("10", "hearts");
        System.out.println(card51);
        Card card52= new Card ("10", "diamonds");
        System.out.println(card52);

    }
}
